/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface StPopupMenu {
    'backgroundColor': string;
    'borderColor': string;
    'borderWidth': string;
    'delay': number;
    'target': string;
    'trigger': string;
  }
  interface StPopupMenuAttributes extends StencilHTMLAttributes {
    'backgroundColor'?: string;
    'borderColor'?: string;
    'borderWidth'?: string;
    'delay'?: number;
    'onHide'?: (event: CustomEvent) => void;
    'onShow'?: (event: CustomEvent) => void;
    'target'?: string;
    'trigger'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'StPopupMenu': Components.StPopupMenu;
  }

  interface StencilIntrinsicElements {
    'st-popup-menu': Components.StPopupMenuAttributes;
  }


  interface HTMLStPopupMenuElement extends Components.StPopupMenu, HTMLStencilElement {}
  var HTMLStPopupMenuElement: {
    prototype: HTMLStPopupMenuElement;
    new (): HTMLStPopupMenuElement;
  };

  interface HTMLElementTagNameMap {
    'st-popup-menu': HTMLStPopupMenuElement
  }

  interface ElementTagNameMap {
    'st-popup-menu': HTMLStPopupMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
